### ISSUE TITLE
How and where to run the "MdMergeAll"-command?

### ISSUE THREAD

**Issue by Guevarabrik** [Kevenin/Markdown-Include#8]
Hi,
i have no idea where and how to run the commands, could you please describe this part ?

**Comment by Kevenin** [comment]
Hi,
Thanks for using my extension.

Have you checked the examples folder?
If you haven't, it shows how to put the tags used by the extention in the md files. As for how to use the commands, they can be called either from the context menu (right-click) while editing an md, or from the command line (CTRL+SHIFT+P).

Hope this helps

**Comment by Guevarabrik** [comment]
Hi, 
thx for your help, it works now 👍 
the tags were not problem, this part was clearly understood. i just didnt know how to run the command, because i tried the command in the cmd and it didnt work.

just a suggestion, maybe you can describe the part with the command a bit better for future users.

thx very much 👍

**Comment by Kevenin** [comment]
Alright, will do.
I'll close this now.
