### ISSUE TITLE
Extension only works on Windows because of hardcoded path divider "\"

### ISSUE THREAD

**Issue by alexziskind1** [Kevenin/Markdown-Include#9]
I tried this on a Mac and the plugin fails because it is concatenating "\" into the path instead of using path.join(). 
This worked like a charm on my Windows machine though. Thanks for creating it.

**Comment by Kevenin** [comment]
You're welcome! Ill try to fix that so that it works on both!

**Comment by Kevenin** [comment]
I've published a fix.
Let me know if theres any more trouble!

**Comment by alexziskind1** [comment]
That was incredibly fast! Thanks for the fix. I've just verified it works on the Mac.
